name: Deploy GitHub Pages

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Build web demo
        run: |
          cd web-example
          npm install
          npm run build
          sudo mkdir -p ../_site/web-example/demo
          sudo mv build/* ../_site/web-example/demo
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:  
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
